on: [push]

name: Build and push be image to github packages and docker hub

jobs:
  build:
    name: Build and push be image to github packages and docker hub
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Install musicmash and musicmashctl
        run: |
          go install -v -mod=vendor ./cmd/...

      - name: Test whole code
        run: |
          go test -v -mod=vendor ./internal/...

      - name: Install and run lints
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GITHUB_WORKSPACE v1.25.0
          $GITHUB_WORKSPACE/golangci-lint -v run

          go get -u github.com/mgechev/revive
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./cmd/...
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./internal/...
          $(go env GOPATH)/bin/revive --config ./.revive.toml --formatter stylish ./pkg/...

      - name: Pull latest images
        run: |
          docker pull $IMAGE_NAME:latest || true
          docker pull $IMAGE_NAME-builder-stage:latest || true

      - name: Build the Docker image
        run: |
          docker build \
            --target builder \
            --cache-from $IMAGE_NAME-builder-stage:latest \
            -t $IMAGE_NAME-builder-stage \
            .
          docker build \
            --cache-from $IMAGE_NAME-builder-stage:latest \
            --cache-from $IMAGE_NAME:latest \
            --tag $IMAGE_NAME:latest \
            --tag docker.pkg.github.com/$IMAGE_NAME/musicmash:latest \
            .

      - name: Login to hubs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKERHUB_ACTOR: ${{ secrets.DOCKERHUB_ACTOR }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $GITHUB_ACTOR    -p $GITHUB_TOKEN
          docker login                       -u $DOCKERHUB_ACTOR -p $DOCKERHUB_TOKEN

      - name: Push image to hubs
        run: |
          docker push $IMAGE_NAME-builder-stage:latest
          docker push $IMAGE_NAME:latest
          docker push docker.pkg.github.com/$IMAGE_NAME/musicmash:latest

      - name: Logout
        run: |
          docker logout docker.pkg.github.com
          docker logout
